feat: Add support to make commands run locally
- not using container

diff --git a/module-assets/Makefile b/module-assets/Makefile
--- a/module-assets/Makefile
+++ b/module-assets/Makefile
@@ -55,62 +55,81 @@ docker-run:
 	docker run -it -v $$(pwd):/mnt -v ~/.ssh:/root/.ssh ${DOCKER_REGISTRY}/$(IMAGE) bash
 
 # pre-commit for repos with terraform code
+# Not directly mounting ~/.ssh because we will be changing the permissions, so creating backup and mounting that.
 pre-commit:
 	@if [ -z "$${TF_VAR_ibmcloud_api_key}" ]; then echo "Error: TF_VAR_ibmcloud_api_key is undefined"; exit 1; fi
 	@if [ -z "$${GH_TOKEN}" ]; then echo "Error: GH_TOKEN is undefined"; exit 1; fi
-	# Not directly mounting ~/.ssh because we will be changing the permissions, so creating backup and mounting that.
-	cp -r ~/.ssh /tmp
-	docker run -it -v $$(pwd):/mnt \
+	@run_cmd="make ghe-netrc && \
+			terraform init && \
+			terragrunt run-all init || echo 'Ignoring failure incase this is a non terragrunt project' && \
+			pre-commit run --all-files" && \
+	if [ "$${NO_CONTAINER}" == "true" ]; \
+	then \
+		bash -c "$${run_cmd}"; \
+	else \
+		cp -r ~/.ssh /tmp; \
+		docker run -it -v $$(pwd):/mnt \
 		-v /tmp/.ssh:/root/.ssh \
 		-e TF_VAR_ibmcloud_api_key \
 		-e GH_TOKEN \
 		${DOCKER_REGISTRY}/$(IMAGE) \
 		bash -c "chown -R root /root/.ssh && \
 			chgrp -R root /root/.ssh && \
-			make ghe-netrc && \
-			terraform init && \
-			terragrunt run-all init || echo 'Ignoring failure incase this is a non terragrunt project' && \
-			pre-commit run --all-files"
-	# Cleanup after (must use sudo as dir now owned by root)
-	sudo rm -rf /tmp/.ssh
+			$${run_cmd}"; \
+		sudo rm -rf /tmp/.ssh; \
+	fi
 
 # pre-commit for non-terraform repos
+# Not directly mounting ~/.ssh because we will be changing the permissions, so creating backup and mounting that.
+# After remove /tmp/.ssh (must use sudo as dir now owned by root)
 pre-commit-no-terraform:
-	# Not directly mounting ~/.ssh because we will be changing the permissions, so creating backup and mounting that.
-	cp -r ~/.ssh /tmp
-	docker run -it -v $$(pwd):/mnt \
-		-v /tmp/.ssh:/root/.ssh \
-		${DOCKER_REGISTRY}/$(IMAGE) \
-		bash -c "chown -R root /root/.ssh && \
-			pre-commit run --all-files"
-	# Cleanup after (must use sudo as dir now owned by root)
-	sudo rm -rf /tmp/.ssh
+	@run_cmd="pre-commit run --all-files" && \
+	if [ "$${NO_CONTAINER}" == "true" ]; \
+	then \
+		bash -c "$${run_cmd}"; \
+	else \
+		cp -r ~/.ssh /tmp; \
+		docker run -it -v $$(pwd):/mnt \
+			-v /tmp/.ssh:/root/.ssh \
+			${DOCKER_REGISTRY}/$(IMAGE) \
+			bash -c "chown -R root /root/.ssh && \
+				$${run_cmd}"; \
+		sudo rm -rf /tmp/.ssh; \
+	fi
 
 # go mod tidy
 go-mod-tidy:
 	@cd ${GO_MOD_DIR}; go mod tidy -v ${GO_MOD_ARGS}
 
 # run tests for terraform repos
+# Not directly mounting ~/.ssh because we will be changing the permissions, so creating backup and mounting that.
+# After remove /tmp/.ssh (must use sudo as dir now owned by root)
 run-tests: SHELL:=/bin/bash
-run-tests:
+run-tests: verify-artifactory-credentials-set
 	@if [ -z "$${TF_VAR_ibmcloud_api_key}" ]; then echo "Error: TF_VAR_ibmcloud_api_key is undefined"; exit 1; fi
 	@if [ -z "$${GH_TOKEN}" ]; then echo "Error: GH_TOKEN is undefined"; exit 1; fi
-	# Not directly mounting ~/.ssh because we will be changing the permissions, so creating backup and mounting that.
-	cp -r ~/.ssh /tmp
-	docker run -it -v $$(pwd):/mnt \
-		-v /tmp/.ssh:/root/.ssh \
-		-e IC_API_KEY="$${TF_VAR_ibmcloud_api_key}" \
-		-e GOPROXY \
-		-e GONOSUMDB \
-		-e FORCE_TEST_REGION \
-		-e GH_TOKEN \
-		--env-file <(env| grep 'TRAVIS_\|GH_TOKEN\|TF_VAR_' | cut -f1 -d=) \
-		--env-file ${DOCKER_ENV} \
-		${DOCKER_REGISTRY}/$(IMAGE) \
-		bash -c "chown -R root /root/.ssh && \
-			chgrp -R root /root/.ssh && \
-			make ghe-netrc && \
-			ci/run-tests.sh"
+	@run_cmd="make ghe-netrc && \
+		ci/run-tests.sh" && \
+	if [ "$${NO_CONTAINER}" == "true" ]; \
+	then \
+		bash -c "$${run_cmd}"; \
+	else \
+		cp -r ~/.ssh /tmp; \
+		docker run -it -v $$(pwd):/mnt \
+			-v /tmp/.ssh:/root/.ssh \
+			-e IC_API_KEY="$${TF_VAR_ibmcloud_api_key}" \
+			-e GOPROXY \
+			-e GONOSUMDB \
+			-e FORCE_TEST_REGION \
+			-e GH_TOKEN \
+			--env-file <(env| grep 'TRAVIS_\|GH_TOKEN\|TF_VAR_' | cut -f1 -d=) \
+			--env-file ${DOCKER_ENV} \
+			${DOCKER_REGISTRY}/$(IMAGE) \
+			bash -c "chown -R root /root/.ssh && \
+				chgrp -R root /root/.ssh && \
+				$${run_cmd}"; \
+		sudo rm -rf /tmp/.ssh; \
+	fi
 
 # run tests for terraform repos locally (optionally set RUN env var to a regular expression that matches the test(s) name that you only want to run. e.g. `make run-tests-local RUN=TestRunApplyTest`)
 run-tests-local:
@@ -120,46 +139,66 @@ run-tests-local:
 # run unit tests for golang
 run-go-module-tests:
 	@if [ -z "$${GH_TOKEN}" ]; then echo "Error: GH_TOKEN is undefined"; exit 1; fi
+	@run_cmd="go test ./... -count=1 -v -timeout 5m" && \
+	if [ "$${NO_CONTAINER}" == "true" ]; \
+	then \
+		bash -c "$${run_cmd}"; \
+	else \
 	docker run -it -v $$(pwd):/mnt \
 		-e GOPROXY \
 		-e GONOSUMDB \
 		-e GH_TOKEN \
 		${DOCKER_REGISTRY}/$(IMAGE) \
-		bash -c "go test ./... -count=1 -v -timeout 5m"
+		bash -c "$${run_cmd}"; \
+	fi
+
 
 # TODO: Remove this command once all travis files have beeb migrated to use make pre-commit-sweeper
 doc-sweeper: pre-commit-sweeper
 
+# Not directly mounting ~/.ssh because we will be changing the permissions, so creating backup and mounting that.
+# After remove /tmp/.ssh (must use sudo as dir now owned by root)
 pre-commit-sweeper:
 	@if [ -z "$${TF_VAR_ibmcloud_api_key}" ]; then echo "Error: TF_VAR_ibmcloud_api_key is undefined"; exit 1; fi
 	@if [ -z "$${GH_TOKEN}" ]; then echo "Error: GH_TOKEN is undefined"; exit 1; fi
-	# Not directly mounting ~/.ssh because we will be changing the permissions, so creating backup and mounting that.
-	cp -r ~/.ssh /tmp
-	docker run -it -v $$(pwd):/mnt \
-		-v /tmp/.ssh:/root/.ssh \
-		-e TRAVIS \
-		-e TRAVIS_PULL_REQUEST \
-		-e TRAVIS_PULL_REQUEST_BRANCH \
-		-e TF_VAR_ibmcloud_api_key \
-		-e GH_TOKEN \
-		${DOCKER_REGISTRY}/$(IMAGE) \
-		bash -c "chown -R root /root/.ssh && \
-			chgrp -R root /root/.ssh && \
-			make ghe-netrc && \
-			ci/pre-commit-sweeper.sh"
-	# Cleanup after (must use sudo as dir now owned by root)
-	sudo rm -rf /tmp/.ssh
+	@run_cmd="make ghe-netrc && \
+		ci/pre-commit-sweeper.sh" && \
+	if [ "$${NO_CONTAINER}" == "true" ]; \
+	then \
+		bash -c "$${run_cmd}"; \
+	else \
+		cp -r ~/.ssh /tmp; \
+		docker run -it -v $$(pwd):/mnt \
+			-v /tmp/.ssh:/root/.ssh \
+			-e TRAVIS \
+			-e TRAVIS_PULL_REQUEST \
+			-e TRAVIS_PULL_REQUEST_BRANCH \
+			-e TF_VAR_ibmcloud_api_key \
+			-e GH_TOKEN \
+			${DOCKER_REGISTRY}/$(IMAGE) \
+			bash -c "chown -R root /root/.ssh && \
+				chgrp -R root /root/.ssh && \
+				m$${run_cmd}"; \
+		sudo rm -rf /tmp/.ssh; \
+	fi
 
 sem-release:
 	@if [ -z "$${GH_TOKEN}" ]; then echo "Error: GH_TOKEN is undefined"; exit 1; fi
+	@run_cmd="mv -t /mnt /tmp/node_modules /tmp/package-lock.json && \
+		npx semantic-release --no-ci" && \
+	if [ "$${NO_CONTAINER}" == "true" ]; \
+	then \
+		bash -c "$${run_cmd}"; \
+	else \
 	docker run -it -v $$(pwd):/mnt \
 		-v ~/.ssh:/root/.ssh \
 		-e GH_TOKEN \
 		-e CATALOG_TEKTON_WEBHOOK_URL \
 		-e CATALOG_TEKTON_WEBHOOK_TOKEN \
 		${DOCKER_REGISTRY}/$(IMAGE) \
-		bash -c "mv -t /mnt /tmp/node_modules /tmp/package-lock.json && \
-			npx semantic-release --no-ci"
+		bash -c "$${run_cmd}"; \
+	fi
+
 
 # Create entry in ~/.netrc for cm.globalcatalog.cloud.ibm.com using IAM bearer token
 netrc:
