ci: cleanup Makefile (#493)
* ci: cleanup Makefile

* ci: pr comments

diff --git a/module-assets/Makefile b/module-assets/Makefile
--- a/module-assets/Makefile
+++ b/module-assets/Makefile
@@ -12,7 +12,7 @@ endif
 export
 
 # explicitly tell Make these commands not associated with files
-.PHONY: all dependency-install-darwin-linux dependency-pre-commit docker-pull docker-run pre-commit pre-commit-no-terraform go-mod-tidy run-tests run-tests-local run-go-module-tests renovate-sweeper sem-release netrc ghe-netrc
+.PHONY: all dependency-install-darwin-linux dependency-pre-commit docker-pull docker-run pre-commit pre-commit-no-terraform go-mod-tidy run-tests run-tests-local run-go-module-tests renovate-sweeper netrc ghe-netrc
 
 #
 # simply expanded variables
@@ -88,180 +88,44 @@ docker-run:
 #
 
 # pre-commit for repos with terraform code
-# (in container approach, not directly mounting ~/.ssh or ~/.netrc because we will be changing the permissions, so creating backup and mounting that instead)
-pre-commit:
-ifdef GHE
-ifndef GH_TOKEN
-	$(error Error: GH_TOKEN is undefined)
-endif
-endif
-	@run_cmd="make ghe-netrc && \
-			terraform init && \
-			terragrunt run-all init || echo 'Ignoring failure incase this is a non terragrunt project' && \
-			pre-commit run --all-files" && \
-	if [ "$${NO_CONTAINER}" = "true" ]; \
-	then \
-		bash -c "$${run_cmd}"; \
-	else \
-		cp -r ~/.ssh /tmp && \
-		cp ~/.netrc /tmp && \
-		${CONTAINER_RUNTIME} run -it -v $$(pwd):/mnt \
-			-v /tmp/.ssh:/root/.ssh \
-			-v /tmp/.netrc:/root/.netrc \
-			-e GH_TOKEN \
-			${DOCKER_REGISTRY}/$(IMAGE) \
-			bash -c "chown -R root /root/.ssh /root/.netrc && \
-				chgrp -R root /root/.ssh /root/.netrc && \
-				git config --global --add safe.directory \$$PWD && \
-				$${run_cmd}"; \
-		exitCode=$$?; \
-		sudo rm -rf /tmp/.ssh /tmp/.netrc; \
-		exit $${exitCode}; \
-	fi
+pre-commit: ghe-netrc
+	@echo "Running terraform init .."
+	@terraform init
+	@echo
+	@echo "Running terragrunt run-all init .."
+	@terragrunt run-all init || echo 'Ignoring failure incase this is a non terragrunt project'
+	@echo "Running pre-commit hooks .."
+	@pre-commit run --all-files
 
 # pre-commit for non-terraform repos
-# (in container approach, not directly mounting ~/.ssh or ~/.netrc because we will be changing the permissions, so creating backup and mounting that instead)
 pre-commit-no-terraform:
-	@run_cmd="pre-commit run --all-files" && \
-	if [ "$${NO_CONTAINER}" = "true" ]; \
-	then \
-		bash -c "$${run_cmd}"; \
-	else \
-		cp -r ~/.ssh /tmp && \
-		cp ~/.netrc /tmp && \
-		${CONTAINER_RUNTIME} run -it -v $$(pwd):/mnt \
-			-v /tmp/.ssh:/root/.ssh \
-			-v /tmp/.netrc:/root/.netrc \
-			${DOCKER_REGISTRY}/$(IMAGE) \
-			bash -c "chown -R root /root/.ssh /root/.netrc && \
-				chgrp -R root /root/.ssh /root/.netrc && \
-				git config --global --add safe.directory \$$PWD && \
-				$${run_cmd}"; \
-		exitCode=$$?; \
-		sudo rm -rf /tmp/.ssh /tmp/.netrc; \
-		exit $${exitCode}; \
-	fi
+	@echo "Running pre-commit hooks .."
+	@pre-commit run --all-files
 
 # run pre-commit checks against renovate PRs, and commit back any changes to the PR (e.g. doc updates, secrets baseline etc)
-# (in container approach, not directly mounting ~/.ssh or ~/.netrc because we will be changing the permissions, so creating backup and mounting that instead)
-renovate-sweeper:
-    ifndef GH_TOKEN
-	   $(error Error: GH_TOKEN is undefined)
-    endif
-	@run_cmd="make ghe-netrc && \
-		ci/renovate-sweeper.sh" && \
-	if [ "$${NO_CONTAINER}" = "true" ]; \
-	then \
-		bash -c "$${run_cmd}"; \
-	else \
-		cp -r ~/.ssh /tmp && \
-		cp ~/.netrc /tmp && \
-		${CONTAINER_RUNTIME} run -it -v $$(pwd):/mnt \
-			-v /tmp/.ssh:/root/.ssh \
-			-v /tmp/.netrc:/root/.netrc \
-			-e TRAVIS \
-			-e TRAVIS_PULL_REQUEST \
-			-e TRAVIS_PULL_REQUEST_BRANCH \
-			-e GH_TOKEN \
-			${DOCKER_REGISTRY}/$(IMAGE) \
-			bash -c "chown -R root /root/.ssh /root/.netrc && \
-				chgrp -R root /root/.ssh /root/.netrc && \
-				git config --global --add safe.directory \$$PWD && \
-				$${run_cmd}"; \
-		exitCode=$$?; \
-		sudo rm -rf /tmp/.ssh /tmp/.netrc; \
-		exit $${exitCode}; \
-	fi
+renovate-sweeper: ghe-netrc
+	ci/renovate-sweeper.sh
 
 #
 # tests
 #
 
 # run tests for terraform repos (pipeline execution only - not for local usage)
-# (in container approach, not directly mounting ~/.ssh because we will be changing the permissions, so creating backup and mounting that instead)
 run-tests: SHELL:=/bin/bash
-run-tests:
-	@if [ -z "$${TF_VAR_ibmcloud_api_key}" ]; then echo "Error: TF_VAR_ibmcloud_api_key is undefined"; exit 1; fi
-
-ifdef GHE
-ifndef GH_TOKEN
-	$(error Error: GH_TOKEN is undefined)
-endif
-endif
-
-	@run_cmd="make ghe-netrc && \
-		ci/run-tests.sh" && \
-	if [ "$${NO_CONTAINER}" == "true" ]; \
-	then \
-		bash -c "$${run_cmd}"; \
-	else \
-		cp -r ~/.ssh /tmp && \
-		${CONTAINER_RUNTIME} run -it -v $$(pwd):/mnt \
-			-v /tmp/.ssh:/root/.ssh \
-			-e IC_API_KEY="$${TF_VAR_ibmcloud_api_key}" \
-			-e GOPROXY \
-			-e GONOSUMDB \
-			-e FORCE_TEST_REGION \
-			--env-file <(env| grep 'TRAVIS\|GH_TOKEN\|TF_VAR_\|MZ_' | cut -f1 -d=) \
-			--env-file ${DOCKER_ENV} \
-			${DOCKER_REGISTRY}/$(IMAGE) \
-			bash -c "chown -R root /root/.ssh && \
-				chgrp -R root /root/.ssh && \
-				git config --global --add safe.directory \$$PWD && \
-				$${run_cmd}"; \
-		exitCode=$$?; \
-		sudo rm -rf /tmp/.ssh; \
-		exit $${exitCode}; \
-	fi
+run-tests: ghe-netrc
+	ci/run-tests.sh
 
 # run tests for terraform repos locally
-# (optionally set RUN env var to a regular expression that matches the test(s) name that you only want to run. e.g. `make run-tests-local RUN=TestRunApplyTest`)
 run-tests-local:
-	@if [ -z "$${TF_VAR_ibmcloud_api_key}" ]; then echo "Error: TF_VAR_ibmcloud_api_key is undefined"; exit 1; fi
 	cd ${GO_TEST_DIR} && go test -run ${RUN} -count=1 -v -timeout 300m
 
 # run unit tests for golang projects
 run-go-module-tests:
-	@run_cmd="go test \$$(go list ./... | grep -v /common-dev-assets/) -count=1 -v -timeout 5m" && \
-	if [ "$${NO_CONTAINER}" = "true" ]; \
-	then \
-		bash -c "$${run_cmd}"; \
-	else \
-	${CONTAINER_RUNTIME} run -it -v $$(pwd):/mnt \
-		-e GOPROXY \
-		-e GONOSUMDB \
-		${DOCKER_REGISTRY}/$(IMAGE) \
-		bash -c "$${run_cmd}"; \
-	fi
+	go test $$(go list ./... | grep -v /common-dev-assets/) -count=1 -v -timeout 5m
 
 # go mod tidy
 go-mod-tidy:
 	@cd ${GO_MOD_DIR}; go mod tidy -v ${GO_MOD_ARGS}
-
-#
-# release
-#
-
-sem-release:
-ifdef GHE
-ifndef GH_TOKEN
-	$(error Error: GH_TOKEN is undefined)
-endif
-endif
-	@run_cmd="mv -t /mnt /tmp/node_modules /tmp/package-lock.json && \
-		npx semantic-release --no-ci" && \
-	if [ "$${NO_CONTAINER}" = "true" ]; \
-	then \
-		bash -c "$${run_cmd}"; \
-	else \
-	${CONTAINER_RUNTIME} run -it -v $$(pwd):/mnt \
-		-v ~/.ssh:/root/.ssh \
-		-e GH_TOKEN \
-		-e CATALOG_TEKTON_WEBHOOK_URL \
-		-e CATALOG_TEKTON_WEBHOOK_TOKEN \
-		${DOCKER_REGISTRY}/$(IMAGE) \
-		bash -c "$${run_cmd}"; \
-	fi
 
 #
 # netrc
@@ -279,7 +143,7 @@ netrc:
 	sleep 5
 
 
-# Create entry in ~/.netrc for github.ibm.com using $GH_TOKEN
+# Create entry in ~/.netrc for github.ibm.com using $GH_TOKEN (no action taken if github.com detected)
 ghe-netrc:
 ifdef GHE
 ifndef GH_TOKEN
@@ -291,6 +155,4 @@ endif
 	else \
 		echo "Found entry already exists in ~/.netrc for github.ibm.com. Taking no action."; \
 	fi
-else
-	@echo "Not in GHE skipping ghe-netrc modification"
 endif
